version: '3.8'

services:
  # Next.js web application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/dggames
      - MONGODB_DB=dggames
      - NEXTAUTH_URL=https://grokgames.dev
      # Ensure NEXTAUTH_SECRET has a default value if not provided
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-SsT0LBAqH0DJtL64PV78L9LBkRIllasBPMszMUpbKH0=}
      # OAuth provider credentials
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - TWITTER_CLIENT_ID=${TWITTER_CLIENT_ID}
      - TWITTER_CLIENT_SECRET=${TWITTER_CLIENT_SECRET}
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    # depends_on:
    #   mongo:
    #     condition: service_healthy
    restart: unless-stopped

  # MongoDB database
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=dggames
    # healthcheck:
    #   test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 10s
    restart: unless-stopped

volumes:
  mongodb_data: 